/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * NEXUS OFFICIAL PIXEL-ART PENGUIN MASCOT
 * Canonical 22x26 Pixel Grid
 *
 * Visual Character Direction:
 * - "A tiny researcher who accidentally lives inside NEXUS"
 * - Original NEXUS silhouette with asymmetric top tuft, compact posture, and signature orange chest X pin
 * - Palette:
 *   - Primary Near-black / Charcoal coat: #151311
 *   - Deep shadow / crevice: #0D0C0B
 *   - Subtle warm-charcoal edge / rim tone: #2A2622
 *   - Feather tuft highlight: #3E3933
 *   - Warm cream face mask & belly: #F3EEE5
 *   - Warm sand shading: #DDD6C9
 *   - Deep pupil: #0A0A09
 *   - Pure white eye catchlight: #FFFFFF
 *   - NEXUS Signature Orange: #EF5A2A
 *   - Light orange highlight: #FF7648
 *   - Dark orange shadow: #C94218
 */

export const PENGUIN_COLORS: Record<string, string> = {
  ".": "transparent",
  "K": "#151311",
  "D": "#0D0C0B",
  "S": "#2A2622",
  "H": "#3E3933",
  "C": "#F3EEE5",
  "G": "#DDD6C9",
  "E": "#0A0A09",
  "W": "#FFFFFF",
  "O": "#EF5A2A",
  "L": "#FF7648",
  "F": "#C94218",
  "R": "#EF5A2A"
};

export type PenguinFrameKey =
  | 'idle'
  | 'blink'
  | 'happy'
  | 'curious'
  | 'look_left'
  | 'look_right'
  | 'look_up'
  | 'surprised'
  | 'wave'
  | 'wave_smile'
  | 'peek_bottom'
  | 'peek_bottom_happy'
  | 'peek_right'
  | 'inspect'
  | 'admire'
  | 'shy'
  | 'walk_1'
  | 'walk_2'
  | 'nexus_touch'
  | 'struggle_start'
  | 'struggle_left'
  | 'struggle_right'
  | 'struggle_up'
  | 'struggle_down'
  | 'recover'
  | 'annoyed';

export const PIXEL_HEART: string[] = [
  ".RR.RR.",
  "RRRRRRR",
  "RRRRRRR",
  ".RRRRR.",
  "..RRR..",
  "...R...",
  "......."
];

export const PENGUIN_FRAMES: Record<PenguinFrameKey, string[]> = {
  "idle": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "blink": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCCCCCKKCCCCCKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "happy": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    ".SSKKKKKCCCCCCCCKKKKSS",
    "SKKKKKCCC.O.O.CCCKKKKS",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "curious": [
    "........SH............",
    ".......SHKK...........",
    ".....SSKKKKKKKKKKSS...",
    "....SKKKKKKKKKKKKKKS..",
    "...SKKKKKKKKKKKKKKKKS.",
    "...SKKKCCCCKKCCCCKKKS.",
    "...SKKCWEECKKCWECKKS..",
    "...SKKCEEECKKCEECKKS..",
    "...SKKCCCCCOOOCCCCKS..",
    "...SKKCCCCOLOOCCCCKS..",
    "...SKKKCCCCFFCCCCKKS..",
    "....SKKKKCCCCCCCCKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "look_left": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKWECCKCKKWECCKKS..",
    "..SKKEECCKCKKEECCKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "look_right": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCCWEKKCKCCWEKKS..",
    "..SKKCCEEKKCKCCEEKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "look_up": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKKCCCCCCCCCCKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "surprised": [
    ".......SHH............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKCWWECKKCWECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCCCCCKKOCCCCKKS..",
    "..SKKCCCCOEEOCCCCKKS..",
    "..SKKKCCCCOOOCCCCKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SSKKKKCCCCCCCCKKKKSS",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "wave": [
    ".......SH.............",
    "......SHKK............",
    "...SSSKKKKKKKKKKSS....",
    "..SKKSKKKKKKKKKKKKS...",
    ".SKK.SKKKKKKKKKKKKKS..",
    "SKK..SKKKCCCCKKCCCCKKS",
    "SKK..SKKCWEECKKCWEECKS",
    ".SKK.SKKCEEECKKCEEECKS",
    "..SKKSKKCCCCCOOOCCCCKS",
    "...SSSKKKCCCCOLOOCCKKS",
    ".....SKKKCCCCFFCCCCKKS",
    "....SKKKKCCCCCCCCKKKS.",
    "...SKKKKKCCCCCCCCKKKKS",
    "..SKKKCCC.O.O.CCCKKKS.",
    "..SKKCCCC..L..CCCCKKS.",
    "..SKKKCCC.O.O.CCCKKKS.",
    "..SKKCCCCCCCCCCCCKKKS.",
    "..SKKCCCCCCCCCCCCKKKS.",
    "...SKKGGCCCCCCCCGGKKS.",
    "....SKKGGGGGGGGGGKKS..",
    ".....SKKKKKKKKKKKKS...",
    "......SKKKKKKKKKKS....",
    ".....SOOOOO..OOOOOS...",
    "....LOOOOOO..OOOOOOL..",
    "....FOOOOO....OOOOOF..",
    "......................"
  ],
  "wave_smile": [
    ".......SH.............",
    "......SHKK............",
    "...SSSKKKKKKKKKKSS....",
    "..SKKSKKKKKKKKKKKKS...",
    ".SKK.SKKKKKKKKKKKKKS..",
    "SKK..SKKKCCCCKKCCCCKKS",
    "SKK..SKKCEEECKKCEEECKS",
    ".SKK.SKKCWEECKKCWEECKS",
    "..SKKSKKCCCCCOOOCCCCKS",
    "...SSSKKKCCCCOLOOCCKKS",
    ".....SKKKCCCCFFCCCCKKS",
    "....SKKKKCCCCCCCCKKKS.",
    "...SKKKKKCCCCCCCCKKKKS",
    "..SKKKCCC.O.O.CCCKKKS.",
    "..SKKCCCC..L..CCCCKKS.",
    "..SKKKCCC.O.O.CCCKKKS.",
    "..SKKCCCCCCCCCCCCKKKS.",
    "..SKKCCCCCCCCCCCCKKKS.",
    "...SKKGGCCCCCCCCGGKKS.",
    "....SKKGGGGGGGGGGKKS..",
    ".....SKKKKKKKKKKKKS...",
    "......SKKKKKKKKKKS....",
    ".....SOOOOO..OOOOOS...",
    "....LOOOOOO..OOOOOOL..",
    "....FOOOOO....OOOOOF..",
    "......................"
  ],
  "peek_bottom": [
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "SSSSSSSSSSSSSSSSSSSSSS"
  ],
  "peek_bottom_happy": [
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    "......................",
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "SSSSSSSSSSSSSSSSSSSSSS"
  ],
  "peek_right": [
    "...........SH.........",
    "..........SHKK........",
    "........SSKKKK........",
    ".......SKKKKKK........",
    "......SKKKKKKK........",
    "......SKKKCCCC........",
    "......SKKCWEEC........",
    "......SKKCEEEC........",
    "......SKKCCCCC........",
    "......SKKCCCCO........",
    "......SKKKCCCC........",
    ".......SKKKKCC........",
    "......SKKKKKCC........",
    ".....SKKKKCCC.........",
    ".....SKKKCCCC.........",
    ".....SKKKKCCC.........",
    ".....SKKKCCCCC........",
    ".....SKKKCCCCC........",
    "......SKKGGCCC........",
    ".......SKKGGGG........",
    "........SKKKKK........",
    ".........SKKKK........",
    "........SOOOOO........",
    ".......LOOOOOO........",
    ".......FOOOOO.........",
    "......................"
  ],
  "inspect": [
    ".....SH...............",
    "....SHKK..............",
    "..SSKKKKKKKKKKSS......",
    ".SKKKKKKKKKKKKKKS.....",
    "SKKKKKKKKKKKKKKKKS....",
    "SKKKCCCCKKCCCCKKKS....",
    "SKKCWEECKKCWEECKKS....",
    "SKKCEEECKKCEEECKKS....",
    ".SKKCCCCCOOOCCCCKS....",
    ".SKKCCCCOLOOCCCCKS....",
    "..SKKCCCCFFCCCCKKS....",
    "...SKKKCCCCCCCCKKKS...",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "admire": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWWECKKCWWECKKS..",
    "..SKKCEWECKKCEWECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "shy": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCCWEKKCKCCWEKKS..",
    "..SKKCCEEKKCKCCEEKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "walk_1": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "...SOOOOOO............",
    "..LOOOOOOO...SOOOO....",
    "..FOOOOOOF...FOOOF....",
    "......................"
  ],
  "walk_2": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "............SOOOOOO...",
    "....SOOOO...LOOOOOOO..",
    "....FOOOF...FOOOOOOF..",
    "......................"
  ],
  "nexus_touch": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWEECKKCWEECKKS..",
    "..SKKCEEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKCCC.O.O.CCCKKKSS",
    ".SKKKCCCC..L..CCCCKKOO",
    ".SKKKKCCC.O.O.CCCKKKSS",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "struggle_start": [
    ".......SHH............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKCWWECKKCWECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCCCCCKKOCCCCKKS..",
    "..SKKCCCCOEEOCCCCKKS..",
    "..SKKKCCCCOOOCCCCKKS..",
    ".SSKKKKKCCCCCCCCKKKKSS",
    "SKKKKKKKCCCCCCCCKKKKKS",
    "SKKKKKCCC.O.O.CCCKKKKS",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "struggle_left": [
    "....SH................",
    "...SHKK...............",
    ".SSKKKKKKKKKKSS.......",
    "SKKKKKKKKKKKKKKS......",
    "SKKKKKKKKKKKKKKKKS....",
    "SKKKCCCCKKCCCCKKKS....",
    "SKKCWWECKKCWECKKS.....",
    "SKKCEEECKKCEECKKS.....",
    ".SKKCCCCCOOOCCCCKS....",
    ".SKKCCCCOEEOCCCCKS....",
    "..SKKKCCCCOOCCCCKKS...",
    "SSSKKKKKCCCCCCCCKKKSS.",
    "SKKKKKKKCCCCCCCCKKKKKS",
    ".SKKKKCCC.O.O.CCCKKKKS",
    "..SKKKCCCC..L..CCCCKKS",
    "..SKKKKCCC.O.O.CCCKKKS",
    "..SKKKCCCCCCCCCCCCKKKS",
    "...SKKCCCCCCCCCCCCKKKS",
    "....SKKGGCCCCCCCCGGKKS",
    ".....SKKGGGGGGGGGGKKS.",
    "......SKKKKKKKKKKKKS..",
    ".......SKKKKKKKKKKS...",
    "......SOOOOO..OOOOOS..",
    ".....LOOOOOO..OOOOOOL.",
    ".....FOOOOO....OOOOOF.",
    "......................"
  ],
  "struggle_right": [
    "................SH....",
    "...............SHKK...",
    ".......SSKKKKKKKKKKSS.",
    "......SKKKKKKKKKKKKKKS",
    "....SKKKKKKKKKKKKKKKKS",
    "....SKKKCCCCKKCCCCKKKS",
    ".....SKKCWWECKKCWECKKS",
    ".....SKKCEEECKKCEECKKS",
    "....SKCCCCCOOOCCCCKKS.",
    "....SKCCCCCOEEOCCCKKS.",
    "...SKKCCCCOOCCCCKKKS..",
    ".SSKKKCCCCCCCCKKKKSSS.",
    "SKKKKKCCCCCCCCKKKKKKS.",
    "SKKKKCCC.O.O.CCCKKKKS.",
    "SKKCCCC..L..CCCCKKKS..",
    "SKKKCCC.O.O.CCCKKKKS..",
    "SKKKCCCCCCCCCCCCKKKS..",
    "SKKKCCCCCCCCCCCCKKKS..",
    "SKKGGCCCCCCCCGGKKS....",
    ".SKKGGGGGGGGGGKKS.....",
    "..SKKKKKKKKKKKKS......",
    "...SKKKKKKKKKKS.......",
    "..SOOOOO..OOOOOS......",
    ".LOOOOOO..OOOOOOL.....",
    ".FOOOOO....OOOOOF.....",
    "......................"
  ],
  "struggle_up": [
    ".......SHH............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKCWWECKKCWECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCCCCCKKOCCCCKKS..",
    "..SKKCCCCOEEOCCCCKKS..",
    "..SKKKCCCCOOOCCCCKKS..",
    "SSSKKKKKCCCCCCCCKKKSSS",
    "SKKKKKKKCCCCCCCCKKKKKS",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKCCCCCCCCCCCCKKS..",
    "...SKKGGCCCCCCCCGGKS..",
    "....SKKGGGGGGGGGGKS...",
    ".....SKKKKKKKKKKKS....",
    "......SKKKKKKKKKS.....",
    "......SOOO...SOOO.....",
    ".....LOOOO...LOOOO....",
    ".....FOOOF...FOOOF....",
    "......................"
  ],
  "struggle_down": [
    "......................",
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCWWECKKCWECKKS...",
    "..SKKCEEECKKCEECKKS...",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    ".SSKKKCCCCFFCCCCKKKSS.",
    "SKKKKKKKCCCCCCCCKKKKKS",
    "SKKKKKCCC.O.O.CCCKKKKS",
    "SKKKCCCC...L...CCCCKKS",
    "SKKKKKCCC.O.O.CCCKKKKS",
    "SKKKCCCCCCCCCCCCKKKKKS",
    "SKKKCCCCCCCCCCCCKKKKKS",
    ".SKKKGGCCCCCCCCGGKKKS.",
    "..SKKKGGGGGGGGGGKKKS..",
    "...SKKKKKKKKKKKKKKS...",
    "....SKKKKKKKKKKKKS....",
    "...SOOOOOO..OOOOOOS...",
    "..LOOOOOOO..OOOOOOOL..",
    "..FOOOOOOF..FOOOOOOF..",
    "......................"
  ],
  "recover": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCEEECKKCWEECKKS..",
    "..SKKCWEECKKCEEECKKS..",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOLOOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SSKKKKCCCCCCCCKKSS..",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCC..L..CCCCKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ],
  "annoyed": [
    ".......SH.............",
    "......SHKK............",
    "....SSKKKKKKKKKKSS....",
    "...SKKKKKKKKKKKKKKS...",
    "..SKKKKKKKKKKKKKKKKS..",
    "..SKKKCCCCKKCCCCKKKS..",
    "..SKKCEEECKKCWEEKKS...",
    "..SKKCEEECKKCEEEKKS...",
    "..SKKCCCCCOOOCCCCKKS..",
    "..SKKCCCCOFFOCCCCKKS..",
    "..SKKKCCCCFFCCCCKKKS..",
    "...SKKKKCCCCCCCCKKKS..",
    "..SKKKKKCCCCCCCCKKKKS.",
    ".SKKKKSSS.O.O.SSSKKKS.",
    ".SKKKSSSS..L..SSSSKKS.",
    ".SKKKKCCC.O.O.CCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    ".SKKKCCCCCCCCCCCCKKKS.",
    "..SKKGGCCCCCCCCGGKKS..",
    "...SKKGGGGGGGGGGKKS...",
    "....SKKKKKKKKKKKKS....",
    ".....SKKKKKKKKKKS.....",
    "....SOOOOO..OOOOOS....",
    "...LOOOOOO..OOOOOOL...",
    "...FOOOOO....OOOOOF...",
    "......................"
  ]
};
